/* Animal catalogue. */
const ANIMALS = {
    waldmaus: { id: "waldmaus", name: "Waldmaus", nameEn: "Field Mouse", icon: "fa-paw", rarity: "Common", resource: "wood" },
    spatz: { id: "spatz", name: "Spatz", nameEn: "Sparrow", icon: "fa-feather", rarity: "Common", resource: "berries" },
    mistkaefer: { id: "mistkaefer", name: "Mistkäfer", nameEn: "Dung Beetle", icon: "fa-locust", rarity: "Common", resource: "mushrooms" },
    eichhoernchen: { id: "eichhoernchen", name: "Eichhörnchen", nameEn: "Squirrel", icon: "fa-squirrel", rarity: "Common", resource: { wood: 50, berries: 50 } },
    baummader: { id: "baummader", name: "Baummarder", nameEn: "Pine Marten", icon: "fa-paw", rarity: "Common", resource: { wood: 50, mushrooms: 50 } },
    hase: { id: "hase", name: "Hase", nameEn: "Hare", icon: "fa-paw", rarity: "Common", resource: { berries: 50, mushrooms: 50 } },
    streifenhoernchen: { id: "streifenhoernchen", name: "Streifenhörnchen", nameEn: "Chipmunk", icon: "fa-paw", rarity: "Common", resource: { wood: 67, berries: 33 } },
    buntspecht: { id: "buntspecht", name: "Buntspecht", nameEn: "Great Spotted Woodpecker", icon: "fa-feather", rarity: "Common", resource: { wood: 67, mushrooms: 33 } },
    feldhase: { id: "feldhase", name: "Feldhase", nameEn: "European Hare", icon: "fa-paw", rarity: "Common", resource: { wood: 33, berries: 67 } },
    wildkaninchen: { id: "wildkaninchen", name: "Wildkaninchen", nameEn: "European Rabbit", icon: "fa-paw", rarity: "Common", resource: { berries: 67, mushrooms: 33 } },
    waldschnecke: { id: "waldschnecke", name: "Waldschnecke", nameEn: "Forest Snail", icon: "fa-bug", rarity: "Common", resource: { wood: 33, mushrooms: 67 } },
    grasfrosch: { id: "grasfrosch", name: "Grasfrosch", nameEn: "Common Frog", icon: "fa-frog", rarity: "Common", resource: { berries: 33, mushrooms: 67 } },
    reh: { id: "reh", name: "Reh", nameEn: "Roe Deer", icon: "fa-paw", rarity: "Common", resource: { wood: 33, berries: 33, mushrooms: 33 } },
    rotes_eichhoernchen: { id: "rotes_eichhoernchen", name: "Rotes Eichhörnchen", nameEn: "Red Squirrel", icon: "fa-paw", rarity: "Common", resource: { wood: 50, berries: 25, mushrooms: 25 } },
    zwergkaninchen: { id: "zwergkaninchen", name: "Zwergkaninchen", nameEn: "Dwarf Rabbit", icon: "fa-paw", rarity: "Common", resource: { wood: 25, berries: 50, mushrooms: 25 } },
    wuehlmaus: { id: "wuehlmaus", name: "Wühlmaus", nameEn: "Vole", icon: "fa-paw", rarity: "Common", resource: { wood: 25, berries: 25, mushrooms: 50 } },

    fischotter: { id: "fischotter", name: "Fischotter", nameEn: "River Otter", icon: "fa-otter", rarity: "Uncommon", resource: "wood" },
    kolibri: { id: "kolibri", name: "Kolibri", nameEn: "Hummingbird", icon: "fa-feather-pointed", rarity: "Uncommon", resource: "berries" },
    gluehwurm: { id: "gluehwurm", name: "Glühwürmchen", nameEn: "Firefly", icon: "fa-mosquito", rarity: "Uncommon", resource: "mushrooms" },
    waschbaer: { id: "waschbaer", name: "Waschbär", nameEn: "Raccoon", icon: "fa-shower", rarity: "Uncommon", resource: { wood: 50, berries: 50 } },
    dachs: { id: "dachs", name: "Dachs", nameEn: "Badger", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 50, mushrooms: 50 } },
    igel: { id: "igel", name: "Igel", nameEn: "Hedgehog", icon: "fa-paw", rarity: "Uncommon", resource: { berries: 50, mushrooms: 50 } },
    biber: { id: "biber", name: "Biber", nameEn: "Beaver", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 67, berries: 33 } },
    gleitbeutler: { id: "gleitbeutler", name: "Gleitbeutler", nameEn: "Sugar Glider", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 67, mushrooms: 33 } },
    siebenschlaefer: { id: "siebenschlaefer", name: "Siebenschläfer", nameEn: "Edible Dormouse", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 33, berries: 67 } },
    steinmarder: { id: "steinmarder", name: "Steinmarder", nameEn: "Beech Marten", icon: "fa-paw", rarity: "Uncommon", resource: { berries: 67, mushrooms: 33 } },
    maulwurf: { id: "maulwurf", name: "Maulwurf", nameEn: "Mole", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 33, mushrooms: 67 } },
    erdkroete: { id: "erdkroete", name: "Erdkröte", nameEn: "Common Toad", icon: "fa-frog", rarity: "Uncommon", resource: { berries: 33, mushrooms: 67 } },
    waldschnepfe: { id: "waldschnepfe", name: "Waldschnepfe", nameEn: "Woodcock", icon: "fa-feather", rarity: "Uncommon", resource: { wood: 33, berries: 33, mushrooms: 33 } },
    eichelhaeher: { id: "eichelhaeher", name: "Eichelhäher", nameEn: "Eurasian Jay", icon: "fa-feather", rarity: "Uncommon", resource: { wood: 50, berries: 25, mushrooms: 25 } },
    wildziege: { id: "wildziege", name: "Wildziege", nameEn: "Wild Goat", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 25, berries: 50, mushrooms: 25 } },
    feldhamster: { id: "feldhamster", name: "Feldhamster", nameEn: "European Hamster", icon: "fa-paw", rarity: "Uncommon", resource: { wood: 25, berries: 25, mushrooms: 50 } },

    hirsch: { id: "hirsch", name: "Hirsch", nameEn: "Deer", icon: "fa-horse", rarity: "Rare", resource: "wood" },
    kiwivogel: { id: "kiwivogel", name: "Kiwi-Vogel", nameEn: "Kiwi Bird", icon: "fa-kiwi-bird", rarity: "Rare", resource: "berries" },
    sumpfkroete: { id: "sumpfkroete", name: "Sumpfkröte", nameEn: "Swamp Toad", icon: "fa-frog", rarity: "Rare", resource: "mushrooms" },
    fasan: { id: "fasan", name: "Fasan", nameEn: "Pheasant", icon: "fa-feather", rarity: "Rare", resource: { wood: 50, berries: 50 } },
    wildschwein: { id: "wildschwein", name: "Wildschwein", nameEn: "Wild Boar", icon: "fa-paw", rarity: "Rare", resource: { wood: 50, mushrooms: 50 } },
    fuchs: { id: "fuchs", name: "Fuchs", nameEn: "Fox", icon: "fa-paw", rarity: "Rare", resource: { berries: 50, mushrooms: 50 } },
    elch: { id: "elch", name: "Elch", nameEn: "Moose", icon: "fa-paw", rarity: "Rare", resource: { wood: 67, berries: 33 } },
    schwarzspecht: { id: "schwarzspecht", name: "Schwarzspecht", nameEn: "Black Woodpecker", icon: "fa-feather", rarity: "Rare", resource: { wood: 67, mushrooms: 33 } },
    auerhuhn: { id: "auerhuhn", name: "Auerhuhn", nameEn: "Capercaillie", icon: "fa-feather", rarity: "Rare", resource: { wood: 33, berries: 67 } },
    honigdachs: { id: "honigdachs", name: "Honigdachs", nameEn: "Honey Badger", icon: "fa-paw", rarity: "Rare", resource: { berries: 67, mushrooms: 33 } },
    zobel: { id: "zobel", name: "Zobel", nameEn: "Sable", icon: "fa-paw", rarity: "Rare", resource: { wood: 33, mushrooms: 67 } },
    feuersalamander: { id: "feuersalamander", name: "Feuersalamander", nameEn: "Fire Salamander", icon: "fa-frog", rarity: "Rare", resource: { berries: 33, mushrooms: 67 } },
    rothirsch: { id: "rothirsch", name: "Rothirsch", nameEn: "Red Deer", icon: "fa-paw", rarity: "Rare", resource: { wood: 33, berries: 33, mushrooms: 33 } },
    specht: { id: "specht", name: "Grünspecht", nameEn: "European Green Woodpecker", icon: "fa-feather", rarity: "Rare", resource: { wood: 50, berries: 25, mushrooms: 25 } },
    steinbock: { id: "steinbock", name: "Steinbock", nameEn: "Alpine Ibex", icon: "fa-paw", rarity: "Rare", resource: { wood: 25, berries: 50, mushrooms: 25 } },
    stachelschwein: { id: "stachelschwein", name: "Stachelschwein", nameEn: "Porcupine", icon: "fa-paw", rarity: "Rare", resource: { wood: 25, berries: 25, mushrooms: 50 } },

    flusspferd: { id: "flusspferd", name: "Flusspferd-Wächter", nameEn: "Hippo Guardian", icon: "fa-hippo", rarity: "Epic", resource: "wood" },
    phoenixfink: { id: "phoenixfink", name: "Phönixfink", nameEn: "Phoenix Finch", icon: "fa-fire", rarity: "Epic", resource: "berries" },
    kristallgarnele: { id: "kristallgarnele", name: "Kristallgarnele", nameEn: "Crystal Shrimp", icon: "fa-shrimp", rarity: "Epic", resource: "mushrooms" },
    roterpanda: { id: "roterpanda", name: "Roter Panda", nameEn: "Red Panda", icon: "fa-paw", rarity: "Epic", resource: { wood: 50, berries: 50 } },
    luchs: { id: "luchs", name: "Luchs", nameEn: "Lynx", icon: "fa-paw", rarity: "Epic", resource: { wood: 50, mushrooms: 50 } },
    pilzwichtel: { id: "pilzwichtel", name: "Pilzwichtel", nameEn: "Mushroom Sprite", icon: "fa-wand-magic-sparkles", rarity: "Epic", resource: { berries: 50, mushrooms: 50 } },
    waldtroll: { id: "waldtroll", name: "Waldtroll", nameEn: "Forest Troll", icon: "fa-paw", rarity: "Epic", resource: { wood: 67, berries: 33 } },
    waldwaechter: { id: "waldwaechter", name: "Waldwächter", nameEn: "Forest Guardian", icon: "fa-tree", rarity: "Epic", resource: { wood: 67, mushrooms: 33 } },
    marderhund: { id: "marderhund", name: "Marderhund", nameEn: "Marten", icon: "fa-paw", rarity: "Epic", resource: { wood: 33, berries: 67 } },
    Fischotter: { id: "Fischotter", name: "Fischotter", nameEn: "Eurasian Otter", icon: "fa-paw", rarity: "Epic", resource: { berries: 67, mushrooms: 33 } },
    pilzeule: { id: "pilzeule", name: "Pilzeule", nameEn: "Mushroom Owl", icon: "fa-feather", rarity: "Epic", resource: { wood: 33, mushrooms: 67 } },
    bergmolch: { id: "bergmolch", name: "Bergmolch", nameEn: "Alpine Newt", icon: "fa-frog", rarity: "Epic", resource: { berries: 33, mushrooms: 67 } },
    waldkauz: { id: "waldkauz", name: "Waldkauz", nameEn: "Tawny Owl", icon: "fa-feather", rarity: "Epic", resource: { wood: 33, berries: 33, mushrooms: 33 } },
    waldnymphe: { id: "waldnymphe", name: "Waldnymphe", nameEn: "Wood Nymph", icon: "fa-wand-magic-sparkles", rarity: "Epic", resource: { wood: 50, berries: 25, mushrooms: 25 } },
    murmeltier: { id: "murmeltier", name: "Alpenmurmeltier", nameEn: "Alpine Marmot", icon: "fa-paw", rarity: "Epic", resource: { wood: 25, berries: 50, mushrooms: 25 } },
    dachsiltis: { id: "dachsiltis", name: "Europäischer Iltis", nameEn: "European Polecat", icon: "fa-paw", rarity: "Epic", resource: { wood: 25, berries: 25, mushrooms: 50 } },

    holzgeist: { id: "holzgeist", name: "Holzgeist", nameEn: "Wood Spirit", icon: "fa-tree", rarity: "Legendary", resource: "wood" },
    bluetengeist: { id: "bluetengeist", name: "Blütengeist", nameEn: "Blossom Spirit", icon: "fa-leaf", rarity: "Legendary", resource: "berries" },
    pilzaal: { id: "pilzaal", name: "Pilzaal", nameEn: "Mushroom Eel", icon: "fa-fish", rarity: "Legendary", resource: "mushrooms" },
    waldgeist: { id: "waldgeist", name: "Waldgeist", nameEn: "Forest Spirit", icon: "fa-tree", rarity: "Legendary", resource: { wood: 50, berries: 50 } },
    Pilzhirsch: { id: "pilzhirsch", name: "Pilzhirsch", nameEn: "Fungal Stag", icon: "fa-paw", rarity: "Legendary", resource: { wood: 50, mushrooms: 50 } },
    beerendrache: { id: "beerendrache", name: "Beerendrache", nameEn: "Berry Dragon", icon: "fa-dragon", rarity: "Legendary", resource: { berries: 50, mushrooms: 50 } },
    baumhueter: { id: "baumhueter", name: "Baumhüter", nameEn: "Treant", icon: "fa-tree", rarity: "Legendary", resource: { wood: 67, berries: 33 } },
    baumdrache: { id: "baumdrache", name: "Baumdrache", nameEn: "Tree Dragon", icon: "fa-dragon", rarity: "Legendary", resource: { wood: 67, mushrooms: 33 } },
    Damwild: { id: "damwild", name: "Damwild", nameEn: "Dam Deer", icon: "fa-paw", rarity: "Legendary", resource: { wood: 33, berries: 67 } },
    Hermelin: { id: "hermelin", name: "Hermelin", nameEn: "Stoat", icon: "fa-paw", rarity: "Legendary", resource: { berries: 67, mushrooms: 33 } },
    waldwisent: { id: "waldwisent", name: "Wisent", nameEn: "European Bison", icon: "fa-paw", rarity: "Legendary", resource: { wood: 33, mushrooms: 67 } },
    axolotl: { id: "axolotl", name: "Axolotl", nameEn: "Axolotl", icon: "fa-frog", rarity: "Legendary", resource: { berries: 33, mushrooms: 67 } },
    uralterhirsch: { id: "uralterhirsch", name: "Uralter Hirsch", nameEn: "Ancient Stag", icon: "fa-paw", rarity: "Legendary", resource: { wood: 33, berries: 33, mushrooms: 33 } },
    uralte_dryade: { id: "uralte_dryade", name: "Uralte Dryade", nameEn: "Ancient Dryad", icon: "fa-tree", rarity: "Legendary", resource: { wood: 50, berries: 25, mushrooms: 25 } },
    vielfrass: { id: "vielfrass", name: "Vielfraß", nameEn: "Wolverine", icon: "fa-paw", rarity: "Legendary", resource: { wood: 25, berries: 50, mushrooms: 25 } },
    karakal: { id: "karakal", name: "Karakal", nameEn: "Caracal", icon: "fa-paw", rarity: "Legendary", resource: { wood: 25, berries: 25, mushrooms: 50 } },
    paketbringer: { id: "paketbringer", name: "Paketbringer", nameEn: "Pack Bringer", icon: "fa-box", rarity: "Legendary", resource: { basicPack: 10 }, fixedYield: true, canBoost: false },
    mystischer_kurier: { id: "mystischer_kurier", name: "Mystischer Kurier", nameEn: "Mystical Courier", icon: "fa-envelope", rarity: "Legendary", resource: { mythicPack: 2 }, fixedYield: true, canBoost: false },
    doppelbote: { id: "doppelbote", name: "Doppelbote", nameEn: "Dual Messenger", icon: "fa-person-hiking", rarity: "Legendary", resource: { basicPack: 5, mythicPack: 2 }, fixedYield: true, canBoost: false },
    kristallwaechter: { id: "kristallwaechter", name: "Kristallwächter", nameEn: "Crystal Guardian", icon: "fa-gem", rarity: "Legendary", resource: "crystals", fixedYield: 15, canBoost: true }
};
